### ISSUE TITLE
Github Actions do sprawdzenia PR czy mamy email organizatora

### ISSUE THREAD

**Issue by kaluzaaa** [AzureCommunityPL/azurecommunitypl.github.io#1]
- Zrobienie GA lub bota, który sprawdzi, czy mamy email organizatora (osoba robiącą PR na GH).
- Info jest trzymane w grupie w Mailerlite
- Mail jest polu email, Github id jest w tablicy fields w obiekcie z kluczem key == github 
- API Key i Group ID wrzucamy do zmiennej
- Dokumentacja api-> https://developers.mailerlite.com/reference#subscribers-in-a-group

Edit 2020.08.16 - Zmiana Table na Mailerlite

**Comment by PawelHaracz** [comment]
Rozumiem, że ma być sprawdzenie w table storage czy dany login i email sa na „white” liście jeśli tak to pozwolić, w przeciwnym wypadku zrobic rejent?

**Comment by eklime** [comment]
> Rozumiem, że ma być sprawdzenie w table storage czy dany login i email sa na „white” liście jeśli tak to pozwolić, w przeciwnym wypadku zrobic rejent?

Dokładnie coś w tym stylu - nie chcemy w PRach wymagać maila do organizatora (bo to przecie Public), dlatego zrobimy sobie "bazę" organizatorów z ich mailami do kontaktu żeby móc ich np. ustawiać jako "odbiorca" CFP z kolejnego Issue ;)

**Comment by kaluzaaa** [comment]
@PawelHaracz nie odrzucenie, ale tylko prośba w komentarzu do PR o kontakt na kontakt@azurecommunity.pl

Trochę jak sprawdzenie czy podpisałeś licencji w repo community :)

**Comment by PawelHaracz** [comment]
Spoko, tylko powiedz mi jak ma wyglądać pr? Załóżmy że ja chce złożyć CFP.
Podaje nazwę sesji, opis o czym jest, jakieś tam dane o sobie, miejsce i co jeszcze? Taki PR zostanie automatycznie przypisany do kogoś z organizatorów ?

**Comment by kaluzaaa** [comment]
Chcemy wykorzystać yaml data dla Jekyll (np jak [w mentoring-2020](https://github.com/AzureCommunityPL/mentoring-2020/blob/master/_data/speakers.yaml))

Proces będzie następujący PR modyfikujący o nowe wydarzenie -> weryfikacja czy jest mail -> akceptacja PR -> RSS z yaml data -> Logic App na RSS, który wykona wszystkie reszty (z innych issues).

Na start zakładamy, że będzie jeden wiodący organizator (robiący PR), czyli bierzemy tylko z login GH tego co robi PR.

```
- name: Tomasz Wiśniewski
  photo: TomaszWisniewski.jpg
  ln: https://www.linkedin.com/in/wisniewskitomasz/
  twitter: https://twitter.com/wisniewskit
  url: https://tomaszwisniewski.com
  specialization: Azure Solutions Architect;Azure DevOps;Azure Developer
  facebook:
  github:
  bio: >
    Architekt Azure zajmujacy sie ta technologia od 2011 roku. Fan Azure DevOps, Visual Studio. Zwolennik prostych i skutecznych rozwiązań.
```
